disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - line_length
  - trailing_comma
  - trailing_whitespace
  - type_body_length
  - variable_name
  - vertical_whitespace

opt_in_rules:
  - closure_spacing
  - conditional_returns_on_newline
  - empty_count
  - explicit_init
  - overridden_super_call
  - private_outlet
  - redundant_nil_coalescing
  - switch_case_on_newline

excluded:
  - Carthage
  - External
